= BSL NPM Library

BSL standard library for use across NPM projects.

== Quick start

=== Prerequisites

. https://bun.com[Bun] >= v1.35
. https://nodejs.org/en[Nodejs] >= v24 (LTS)

=== Installation

The project uses https://bun.com[Bun] for package management and is setup with https://bun.com/docs/pm/workspaces[Bun workspaces],
simply run the following from the project root directory to install the dependencies for all
packages:

[source,bash]
----
bun install
----

It's recommended to use https://github.com/nvm-sh/nvm[nvm] to manage you Nodejs version, once
installed, use the following commands from this directory to switch to the correct version:

[source,bash]
----
nvm install

nvm use
----

== Linting and formatting

This project uses https://eslint.org/[Eslint] and https://prettier.io/[Prettier] for linting and
formatting respectively. To run the linter and formatter use following commands:

[source,bash]
----
bun run lint:check
bun run lint:fix

bun run format:check
bun run format:fix
----

== Running unit tests

To run execute the unit tests across all packages with the [Vitest](https://vitest.dev) test runner,
use the following command:

[source,bash]
----
bun run vitest
----

== License

Refer to the `LICENSE` file for details.
